<?php

namespace RoBYCoNTe\FilamentItalia;

class FilamentItaliaTheme
{
    public static function themePath(): string
    {
        return 'vendor/robyconte/filament-italia/resources/css/theme.css';
    }

    public static function overridesPath(): string
    {
        return 'vendor/robyconte/filament-italia/resources/css/overrides.css';
    }

    public static function fontsPath(): string
    {
        return 'vendor/robyconte/filament-italia/resources/css/fonts.css';
    }

    /**
     * Generates a Filament-compatible color palette (shades 50-950) from a base hex color.
     *
     * The base color is mapped to shade 600, and lighter/darker shades
     * are generated by adjusting lightness in HSL color space.
     *
     * @return array<int, string>  Array of hex colors keyed by shade (50, 100, ..., 950)
     */
    public static function generateColorPalette(string $hex): array
    {
        $hex = ltrim($hex, '#');
        $r = hexdec(substr($hex, 0, 2)) / 255;
        $g = hexdec(substr($hex, 2, 2)) / 255;
        $b = hexdec(substr($hex, 4, 2)) / 255;

        $max = max($r, $g, $b);
        $min = min($r, $g, $b);
        $l = ($max + $min) / 2;
        $h = 0;
        $s = 0;

        if ($max !== $min) {
            $d = $max - $min;
            $s = $l > 0.5 ? $d / (2 - $max - $min) : $d / ($max + $min);

            $h = match ($max) {
                $r => (($g - $b) / $d + ($g < $b ? 6 : 0)) / 6,
                $g => (($b - $r) / $d + 2) / 6,
                default => (($r - $g) / $d + 4) / 6,
            };
        }

        $baseLightness = $l;

        $shadeLightness = [
            50 => 0.97,
            100 => 0.90,
            200 => 0.80,
            300 => 0.70,
            400 => 0.60,
            500 => min($baseLightness + 0.08, 0.60),
            600 => $baseLightness,
            700 => max($baseLightness - 0.10, 0.25),
            800 => max($baseLightness - 0.18, 0.18),
            900 => max($baseLightness - 0.25, 0.12),
            950 => max($baseLightness - 0.35, 0.06),
        ];

        $palette = [];

        foreach ($shadeLightness as $shade => $lightness) {
            $palette[$shade] = self::hslToHex($h, $s, $lightness);
        }

        return $palette;
    }

    private static function hslToHex(float $h, float $s, float $l): string
    {
        if ($s === 0.0) {
            $v = (int) round($l * 255);

            return str_pad(dechex($v), 2, '0', STR_PAD_LEFT)
                . str_pad(dechex($v), 2, '0', STR_PAD_LEFT)
                . str_pad(dechex($v), 2, '0', STR_PAD_LEFT);
        }

        $q = $l < 0.5 ? $l * (1 + $s) : $l + $s - $l * $s;
        $p = 2 * $l - $q;

        $r = self::hueToRgb($p, $q, $h + 1 / 3);
        $g = self::hueToRgb($p, $q, $h);
        $b = self::hueToRgb($p, $q, $h - 1 / 3);

        return str_pad(dechex((int) round($r * 255)), 2, '0', STR_PAD_LEFT)
            . str_pad(dechex((int) round($g * 255)), 2, '0', STR_PAD_LEFT)
            . str_pad(dechex((int) round($b * 255)), 2, '0', STR_PAD_LEFT);
    }

    private static function hueToRgb(float $p, float $q, float $t): float
    {
        if ($t < 0) {
            $t += 1;
        }
        if ($t > 1) {
            $t -= 1;
        }
        if ($t < 1 / 6) {
            return $p + ($q - $p) * 6 * $t;
        }
        if ($t < 1 / 2) {
            return $q;
        }
        if ($t < 2 / 3) {
            return $p + ($q - $p) * (2 / 3 - $t) * 6;
        }

        return $p;
    }
}
